namespace FreeTypeBinding
{
    public enum FT_FACE_FLAG : long
    {
        FT_FACE_FLAG_SCALABLE = 1,
        FT_FACE_FLAG_FIXED_SIZES = 2,
        FT_FACE_FLAG_FIXED_WIDTH = 4,
        FT_FACE_FLAG_SFNT = 8,
        FT_FACE_FLAG_HORIZONTAL = 16,
        FT_FACE_FLAG_VERTICAL = 32,
        FT_FACE_FLAG_KERNING = 64,
        FT_FACE_FLAG_FAST_GLYPHS = 128,
        FT_FACE_FLAG_MULTIPLE_MASTERS = 256,
        FT_FACE_FLAG_GLYPH_NAMES = 512,
        FT_FACE_FLAG_EXTERNAL_STREAM = 1024,
        FT_FACE_FLAG_HINTER = 2048,
        FT_FACE_FLAG_CID_KEYED = 4096,
        FT_FACE_FLAG_TRICKY = 8192,
        FT_FACE_FLAG_COLOR = 16384,
        FT_FACE_FLAG_VARIATION = 32768,
        FT_FACE_FLAG_SVG = 65536,
        FT_FACE_FLAG_SBIX = 131072,
        FT_FACE_FLAG_SBIX_OVERLAY = 262144
    }
}