namespace FreeTypeBinding
{
    public enum FT_LOAD : long
    {
        FT_LOAD_DEFAULT = 0,
        FT_LOAD_NO_SCALE = 1,
        FT_LOAD_NO_HINTING = 2,
        FT_LOAD_RENDER = 4,
        FT_LOAD_NO_BITMAP = 8,
        FT_LOAD_VERTICAL_LAYOUT = 16,
        FT_LOAD_FORCE_AUTOHINT = 32,
        FT_LOAD_CROP_BITMAP = 64,
        FT_LOAD_PEDANTIC = 128,
        FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH = 512,
        FT_LOAD_NO_RECURSE = 1024,
        FT_LOAD_IGNORE_TRANSFORM = 2048,
        FT_LOAD_MONOCHROME = 4096,
        FT_LOAD_LINEAR_DESIGN = 8192,
        FT_LOAD_SBITS_ONLY = 16384,
        FT_LOAD_NO_AUTOHINT = 32768,
        FT_LOAD_COLOR = 1048576,
        FT_LOAD_COMPUTE_METRICS = 2097152,
        FT_LOAD_BITMAP_METRICS_ONLY = 4194304,
        FT_LOAD_NO_SVG = 16777216,
        FT_LOAD_ADVANCE_ONLY = 256,
        FT_LOAD_SVG_ONLY = 8388608
    }
}